"""db defaults + cascades + partial unique fix

Revision ID: 15be8f8912cd
Revises: 76219fd660bf
Create Date: 2025-08-31 17:32:13.925195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15be8f8912cd'
down_revision: Union[str, Sequence[str], None] = '76219fd660bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_members_user_id_fkey'), 'room_members', type_='foreignkey')
    op.drop_constraint(op.f('room_members_room_id_fkey'), 'room_members', type_='foreignkey')
    op.create_foreign_key(None, 'room_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'room_members', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('room_tracks_track_id_fkey'), 'room_tracks', type_='foreignkey')
    op.drop_constraint(op.f('room_tracks_added_by_user_id_fkey'), 'room_tracks', type_='foreignkey')
    op.drop_constraint(op.f('room_tracks_room_id_fkey'), 'room_tracks', type_='foreignkey')
    op.create_foreign_key(None, 'room_tracks', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'room_tracks', 'users', ['added_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'room_tracks', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('rooms_host_user_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['host_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('votes_user_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_room_track_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'room_tracks', ['room_track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_room_track_id_fkey'), 'votes', 'room_tracks', ['room_track_id'], ['id'])
    op.create_foreign_key(op.f('votes_user_id_fkey'), 'votes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_host_user_id_fkey'), 'rooms', 'users', ['host_user_id'], ['id'])
    op.drop_constraint(None, 'room_tracks', type_='foreignkey')
    op.drop_constraint(None, 'room_tracks', type_='foreignkey')
    op.drop_constraint(None, 'room_tracks', type_='foreignkey')
    op.create_foreign_key(op.f('room_tracks_room_id_fkey'), 'room_tracks', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('room_tracks_added_by_user_id_fkey'), 'room_tracks', 'users', ['added_by_user_id'], ['id'])
    op.create_foreign_key(op.f('room_tracks_track_id_fkey'), 'room_tracks', 'tracks', ['track_id'], ['id'])
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.create_foreign_key(op.f('room_members_room_id_fkey'), 'room_members', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('room_members_user_id_fkey'), 'room_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
