"""queue indexes and partial unique

Revision ID: 76219fd660bf
Revises: 7a58d137eaa5
Create Date: 2025-08-31 14:16:37.808495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76219fd660bf'
down_revision: Union[str, Sequence[str], None] = '7a58d137eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_room_tracks_room_status', 'room_tracks', ['room_id', 'status'], unique=False)
    op.create_index('uq_room_queued_track', 'room_tracks', ['room_id', 'track_id'], unique=True, postgresql_where=sa.text("status = 'queued'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_room_queued_track', table_name='room_tracks', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('ix_room_tracks_room_status', table_name='room_tracks')
    # ### end Alembic commands ###
