"""model tweaks

Revision ID: cfe0fccab475
Revises: 9b6084475bf8
Create Date: 2025-08-29 12:27:24.552034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfe0fccab475'
down_revision: Union[str, Sequence[str], None] = '9b6084475bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracks_artist', 'tracks', ['artist'], unique=False)
    op.create_index('ix_tracks_title', 'tracks', ['title'], unique=False)
    op.create_table('room_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('added_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'playing', 'played', 'removed', name='track_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_room_tracks_room_id', 'room_tracks', ['room_id'], unique=False)
    op.create_index('ix_room_tracks_track_id', 'room_tracks', ['track_id'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_track_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_vote_value'),
    sa.ForeignKeyConstraint(['room_track_id'], ['room_tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_track_id', 'user_id', name='uq_vote_per_user_per_track')
    )
    op.create_index('ix_votes_room_track_id', 'votes', ['room_track_id'], unique=False)
    op.create_index('ix_votes_user_id', 'votes', ['user_id'], unique=False)
    op.alter_column('room_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index('ix_room_members_room_id', 'room_members', ['room_id'], unique=False)
    op.create_index('ix_room_members_user_id', 'room_members', ['user_id'], unique=False)
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('ix_room_members_user_id', table_name='room_members')
    op.drop_index('ix_room_members_room_id', table_name='room_members')
    op.alter_column('room_members', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('ix_votes_user_id', table_name='votes')
    op.drop_index('ix_votes_room_track_id', table_name='votes')
    op.drop_table('votes')
    op.drop_index('ix_room_tracks_track_id', table_name='room_tracks')
    op.drop_index('ix_room_tracks_room_id', table_name='room_tracks')
    op.drop_table('room_tracks')
    op.drop_index('ix_tracks_title', table_name='tracks')
    op.drop_index('ix_tracks_artist', table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
